### ISSUE TITLE
Potential Website Improvements

### ISSUE THREAD

**Issue by amy-mac** [dtinit/dtinit.github.io#20]
- [x] Currently authors are manually putting in post excerpts when excerpts can be auto-generated
- [x] Nav could stack better on mobile
- [ ] post meta should be column instead of row on mobile
- [ ] FAQ page should probably have in-page links at the top as it expands
- [ ] Add simple footer with copyright and contact info
- [x] data flow image on use cases page is too blurry to read and needs descriptive alt text
- [ ] The index/about really needs to be reorganized

**Comment by lisad** [comment]
* Yes lets auto-generate excerpts BUT allow for over-riding
* Yes lets fix nav
* Post meta: yes please go ahead and fix this up and make other improvements to how the blog post index page looks
* Yes please FAQ page top links
* Yes please footer additions
* Data flow image on use cases page: TBD, I'll follow up in a separate ticket
* Index/about - follow up with a separate ticket.

**Comment by amy-mac** [comment]
Most of this I'm going to wait to do since some of it now depends on the help from Erica etc on redesign

**Comment by lisad** [comment]
Most of this is now done or moved to other tickets
