### ISSUE TITLE
Improve hero background image layout at larger screen widths

### ISSUE THREAD

**Issue by alexbainter** [dtinit/dtinit.github.io#67]
The very top background image and gradient don't play super nicely together at larger screen widths. Here's a screenshot from a maximized browser window at 1440p which is a pretty common scenario IMO:

![Screenshot from 2024-02-15 13-08-36](https://github.com/dtinit/dtinit.github.io/assets/6510436/3f9e8b59-fa62-4691-ab52-99a638ad34bb)

**Comment by lisad** [comment]
great issue.  Do you have a suggestion for fixing it @alexbainter?

**Comment by alexbainter** [comment]
Yep! We could either change the styles for that image so it always stretches to fit while preserving its aspect ratio (don't remember the exact CSS off the top of my head!), and/or we could set a maximum width for that entire swoopy thing such that the image will always fit.

**Comment by lisad** [comment]
If those approaches don't work we can always discuss alternatives!

**Comment by alexbainter** [comment]
Here's how it looks with `background-size: cover` added to `.hero-home`:

Large width
![Screenshot from 2024-02-15 13-32-10](https://github.com/dtinit/dtinit.github.io/assets/6510436/d982edfe-fec1-4eed-98aa-bef7f222c829)

Medium width
![Screenshot from 2024-02-15 13-32-28](https://github.com/dtinit/dtinit.github.io/assets/6510436/15678ed6-e073-4d5d-bb82-13cabb2661d0)

Mobile width

![Screenshot from 2024-02-15 13-34-19](https://github.com/dtinit/dtinit.github.io/assets/6510436/56133d79-ccbd-4731-9cd4-0791881be984)

I can a PR but I'm still getting set up (I had to reinstall my OS this morning :upside_down_face: )

**Comment by alexbainter** [comment]
@lisad Can I get push permissions for this repo? I have a fix for this but can't push my branch
